import Head from 'next/head';
import Link from 'next/link';
import React, { useContext } from 'react';
import { store } from '../utils/store';

export default function Layout({ title, children }) {
  const { state } = useContext(store);
  const { cart } = state;
  return (
    <>
      <Head>
        <title>{title ? title + ' - Amazona' : 'Amazona'}</title>
        <meta name="description" content="Ecommerce Website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between ">
        <header>
          <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/">
              <a className="text-lg font-bold">amazona</a>
            </Link>
            <div>
              <Link href="/cart">
                <a className="p-2">
                  Cart
                  {cart.cartItems.length > 0 && (
                    <span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
                      {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                    </span>
                  )}
                </a>
              </Link>
              <Link href="/login">
                <a className="p-2">Login</a>
              </Link>
            </div>
          </nav>
        </header>
        <main className="container m-auto mt-4 px-4">{children}</main>
        <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright © 2022 Amazona</p>
        </footer>
      </div>
    </>
  );
}

// import Head from 'next/head'
// import Link from 'next/link'
// import React, { useContext } from 'react';
// import { Store } from '../utils/store';

// const Layout = ({ title, children }) => {
//   const { state, dispatch } = useContext(Store);
//   const { cart } = state;
//   return (
//     <>
//       <Head>
//         <title>{title ? title + '- Amazoni' : 'Amazoni'}</title>
//         < meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className='flex min-h-screen flex-col justify-between'>
//         <header>
//           <nav className='h-12 items-center px-4 flex justify-between shadow-md'>
//             <Link href="/">
//               <a className='text-lg font-bold'>Amazoni</a>
//             </Link>
//             <div>
//               <Link href="cart"><a className='p-2' >Cart</a></Link>
//               <Link href="login"><a className='p-2'>Login</a></Link>
//             </div>
//           </nav>
//         </header>
//         <main className="container m-auto px-4 mt-4">{children}</main>
//         <footer className='flex h-10 items-center justify-center shadow-inner'>
//           <p> copy right @ 2022 Amazonii</p>
//         </footer>
//       </div>
//     </>
//   )
// }

// export default Layout